### ISSUE TITLE
Entrypoint and use_shim options

### ISSUE THREAD

**Issue by projecteurlumiere** [dvinciguerra/middleman-importmap#6]
Hello and thank you a lot for this useful extension! Since I don't have much experience with js bundling besides importmaps in Rails, this extension comes as neatest and nicest tool for me.

As for the issue,
I noticed there are two options which are defined, yet not implemented. Namely, specifying the entry point filename & using/not using es module shims.

https://github.com/dvinciguerra/middleman-importmap/blob/0bc93a376408c93a361edd5fa6643186b5dcb1ff/lib/middleman-importmap/extension.rb#L9-L10

Are you planning to implement them? Or can/should I take this and make a PR later? They seem quick and simple.

**Comment by dvinciguerra** [comment]
> Hello and thank you a lot for this useful extension! Since I don't have much experience with js bundling besides importmaps in Rails, this extension comes as neatest and nicest tool for me.

Sorry for the delay in responding and thanks for your message... I'm happy to help. =)


Honestly, I forgot to implement this behaviours. 😅


If you are comfortable helping to write a pull request, it will be very welcome. =)
